name: sneaker_shopping_prokit
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.4
  nb_utils: ^4.4.10
  intl: ^0.17.0
  flutter_vector_icons: ^1.0.0
  google_fonts: ^2.2.0
  url_launcher: ^6.0.17
  cached_network_image: ^3.2.0
  flutter_launcher_icons: ^0.9.2

  # Sneaker Shopping App
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/sneakerShopping/ic_sneaker_logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
   - images/sneakerShopping/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

